[package]
name = "radeco-lib"
version = "0.1.0"
authors = [
	"David Kreuter <dkreuter@gmail.com>",
	"Sushant Dinesh <sushant.dinesh94@gmail.com>"
]

[features]
trace_log = []

[dependencies]
regex = "*"
petgraph = "*"
num = "*"
rustc-serialize = "*"
log = "*"

[dependencies.r2pipe]
git = "https://github.com/radare/r2pipe.rs"

[dependencies.esil]
git = "https://github.com/sushant94/esil-rs"
# path = "../esil-rs"
